### ISSUE TITLE
Issue when trying to use NLTI Start command

### ISSUE THREAD

**Issue by b1llb33** [DDX5/NLTI#1]
when I try to start the service on the server, (NLTI Start), I get an error of "An unexpected error occurred trying to execute that command" I am certain my token and ID are correct, but I'm unsure about the format for the config file.

the format is currently: 

{"Token":"***","clientID":"***","redirectURL":"https://id.twitch.tv/oauth2/","Version":"3.1.0","ChaosMode":false,"Usernames":["billbee"]}

(the *** represents the ID and token I input)

am I missing something?

any help is appreciated,
thanks

**Comment by Multi-Coder-24** [comment]
Could you provide a gist for your latest.log file,
Thanks

**Comment by Multi-Coder-24** [comment]
After checking the code, there is a severe bug in version 3.1.0 However version 3.0.0 does work as expected. I would recommend running version 3.0.0 for the time being

**Comment by b1llb33** [comment]
[latest.log](https://github.com/user-attachments/files/18041262/latest.log)


attached is my log file, I tried running with the 3.0.0 version, but am running into some errors, I'm pretty sure I set up everything right though.

let me know if I can send anything else that might help

**Comment by Multi-Coder-24** [comment]
For Version 3.0.0 you will need to delete the nlti-config and nlti-commands files and have them regenerate

**Comment by b1llb33** [comment]
That worked! thanks for your help!!

**Comment by b1llb33** [comment]
:)
